#!/bin/sh

#==============================================================================
# new-since
# File ID: 26ffabea-02a3-11e7-a69b-db5caa6d21d3
#
# Display number of new repositories since the last update.
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=new-since
VERSION=0.1.0

db=repos.sqlite

opt_help=0
opt_quiet=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-h|--help) opt_help=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Display number of new repositories since the last update.

Usage: $progname [options]

Options:

  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

END
	exit 0
fi

date_to_jday() {
	echo "SELECT julianday('$1');" | sqlite3
}

first() {
	echo -n "
SELECT $1 FROM repos
  ORDER BY date DESC
  LIMIT 2;
" | sqlite3 $db | tail -1
}

latest() {
	echo -n "
SELECT $1 FROM repos
  ORDER BY date DESC
  LIMIT 1;
" | sqlite3 $db
}

insnew() {
	local name="$1"
	echo "
INSERT INTO tmp
  VALUES (
    '$name',
    $(latest $name) - $(first $name)
  );
"
}

totals() {
	echo "
SELECT name, val FROM tmp ORDER BY val DESC, name;
SELECT '----------', '------';
SELECT 'Total', sum(val) FROM tmp;
"
}

make $db >/dev/null || exit

now=$(echo "
SELECT date FROM repos
  ORDER BY date DESC
  LIMIT 1;
" | sqlite3 $db)
jnow=$(date_to_jday "$now")

prev=$(echo "
SELECT date FROM repos
  ORDER BY date DESC
  LIMIT 2;
" | sqlite3 $db | tail -1)
jprev=$(date_to_jday "$prev")

jperiod=$(echo "SELECT $jnow-$jprev;" | sqlite3)

printf '\nNew repos between\n%s UTC\n%s UTC\n(%.04f days):\n\n' \
       "$prev" "$now" "$jperiod"
echo "
.width 10 -6 -9
CREATE TEMPORARY TABLE tmp (name TEXT, val INTEGER);
$(insnew bazaar)
$(insnew cvs)
$(insnew git)
$(insnew mercurial)
$(insnew subversion)
$(totals)
" | sqlite3 -column repos.sqlite
echo

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
